"""Render a shareable gameplay .mp4 (with the generated audio) from a headless AV rollout.

Primes from a real clip, then lets the world model play itself (both players driven by the model
via action dropout) using the real-time inference config. Both first-person views are upscaled
side by side under a caption bar; the model's generated 8 kHz waveform becomes the audio track.

Usage:
    python -m examples.pong.render_video [--seconds 45] [--out examples/pong/assets/demo.mp4]
"""

from __future__ import annotations

import argparse
import struct
import subprocess
import time
from pathlib import Path

import numpy as np
import torch
from einops import rearrange

from mira.world_model.config import WorldModelInferenceConfig
from mira.world_model.multi_wrapper_world_model import MultiWrapperWorldModelConfig

from examples.pong.data import PongData
from examples.pong.play_av import AVSession
from examples.pong.train_wm import CLIP_LEN
from examples.pong.world_model import pong_wm_config
from examples.pong.world_model_av import PongAVMultiWrapper

DEVICE = "cuda"
SCALE = 20  # 16x16 -> 320x320 per view
GAP, HEADER = 12, 46
CAPTION = "every pixel & sound generated by an 11M diffusion model - 1x RTX 5080"


def compose(frame_lr: np.ndarray, header_img: np.ndarray) -> np.ndarray:
    """(16, 32, 3) two-view frame -> upscaled side-by-side canvas under the caption bar."""
    left = np.kron(frame_lr[:, :16], np.ones((SCALE, SCALE, 1), dtype=np.uint8))
    right = np.kron(frame_lr[:, 16:], np.ones((SCALE, SCALE, 1), dtype=np.uint8))
    gap = np.full((16 * SCALE, GAP, 3), 10, dtype=np.uint8)
    row = np.concatenate([left, gap, right], axis=1)
    return np.concatenate([header_img, row], axis=0)


def make_header(width: int) -> np.ndarray:
    from PIL import Image, ImageDraw, ImageFont

    img = Image.new("RGB", (width, HEADER), (11, 14, 20))
    draw = ImageDraw.Draw(img)
    try:
        font = ImageFont.truetype("consola.ttf", 13)
        font_big = ImageFont.truetype("consolab.ttf", 19)
    except OSError:
        font = font_big = ImageFont.load_default()
    draw.text((12, 4), "PONG WORLD MODEL", fill=(219, 226, 239), font=font_big)
    draw.text((12, 26), CAPTION, fill=(139, 149, 171), font=font)
    return np.asarray(img)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--seconds", type=int, default=45)
    parser.add_argument("--steps", type=int, default=2, help="denoising steps (real-time config)")
    parser.add_argument("--out", type=Path, default=Path("examples/pong/assets/demo.mp4"))
    parser.add_argument("--checkpoint", type=Path, default=Path("examples/pong/runs/av/wm_av.pt"))
    args = parser.parse_args()
    args.out.parent.mkdir(parents=True, exist_ok=True)

    torch.manual_seed(1)
    torch.set_float32_matmul_precision("high")
    config = pong_wm_config("examples/pong/runs/codec/codec.pt", multiplayer=True, clip_len=CLIP_LEN)
    model = PongAVMultiWrapper(
        MultiWrapperWorldModelConfig(n_players=2, wm_config=config),
        "examples/pong/runs/av/audio_codec.pt",
    ).to(DEVICE)
    model.load_state_dict(torch.load(args.checkpoint, map_location=DEVICE)["state_dict"])
    model.eval()

    test = PongData("examples/pong/runs/data/test.npz", device=DEVICE, with_audio=True)
    session = AVSession(model, test, WorldModelInferenceConfig(n_diffusion_steps=args.steps))

    n_latent_steps = args.seconds * 10
    drop_both = torch.tensor([True, True], device=DEVICE)  # the model plays both paddles
    frames, audio = [], []
    t0 = time.perf_counter()
    for i in range(n_latent_steps):
        f, a = session.step(np.zeros((2, 2, 2), dtype=np.int32), drop_both)
        frames.extend(f)  # 2 x (16, 32, 3)
        audio.append(a)  # (800,) int16
        if (i + 1) % 100 == 0:
            print(f"rollout {i + 1}/{n_latent_steps} ({time.perf_counter() - t0:.0f}s)", flush=True)

    header = make_header(2 * 16 * SCALE + GAP)
    canvas = [compose(f, header) for f in frames]
    height, width = canvas[0].shape[:2]

    wav_path = args.out.with_suffix(".wav")
    pcm = np.concatenate(audio).tobytes()
    wav_path.write_bytes(
        b"RIFF" + struct.pack("<I", 36 + len(pcm)) + b"WAVEfmt "
        + struct.pack("<IHHIIHH", 16, 1, 1, 8000, 16000, 2, 16) + b"data"
        + struct.pack("<I", len(pcm)) + pcm
    )

    cmd = [
        "ffmpeg", "-y",
        "-f", "rawvideo", "-pix_fmt", "rgb24", "-s", f"{width}x{height}", "-r", "20", "-i", "pipe:",
        "-i", str(wav_path),
        "-c:v", "libx264", "-preset", "slow", "-crf", "18", "-pix_fmt", "yuv420p",
        "-c:a", "aac", "-ar", "44100", "-b:a", "96k", "-shortest", str(args.out),
    ]
    proc = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    for c in canvas:
        proc.stdin.write(c.tobytes())
    proc.stdin.close()
    proc.wait()
    wav_path.unlink()
    print(f"{args.out}: {args.out.stat().st_size / 1e6:.1f} MB, {len(canvas) / 20:.0f}s")

    gif = args.out.with_suffix(".gif")
    subprocess.run(
        ["ffmpeg", "-y", "-ss", "5", "-t", "8", "-i", str(args.out),
         "-vf", "fps=10,scale=480:-1:flags=neighbor,split[s0][s1];[s0]palettegen=max_colors=32[p];[s1][p]paletteuse",
         str(gif)],
        capture_output=True,
    )
    print(f"{gif}: {gif.stat().st_size / 1e6:.1f} MB")


if __name__ == "__main__":
    main()
